runtime: nodejs20
env: standard
service: default

entrypoint: npm start

env_variables:
  MONGO_URI: "mongodb+srv://crm:crm@cluster0.eu4ezjd.mongodb.net/crm"
  ACCESS_TOKEN_SECRET: "htyrtfcdrtfdertfcdrtvcserygbvf"
  REFRESH_TOKEN_SECRET: "iutvdertrdcfrtyhfrtwazswerftf"
  FRONTEND_URL: "https://crmfrontend-dbc12.web.app"
  CLIENT_URL: "https://crmfrontend-dbc12.web.app"
  EMAIL_USER: "crm@refratexindia.net"
  EMAIL_PASS: "nolk qsun sbqy gihd"
  CLOUDINARY_CLOUD_NAME: "dhy1ot6lf"
  CLOUDINARY_API_KEY: "297362761355144"
  CLOUDINARY_API_SECRET: "cI7-DS43YOdJUYmNXlWLSbbgZ-U"
  EMAIL_CRED_KEY: "sdajbcugducigdebvckhvdvfygqwuy126rr"
